---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 12.2.1
  provider: vmware_fusion
  customize:
    memsize: 1024

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04

suites:
- name: default
  run_list:
  - 'recipe[apt]'
  - 'recipe[err]'
  attributes:
    err:
      plugins:
        - name: err-calcbot
          repository: 'git://github.com/gbin/err-calcbot.git'
          revision: 21060b3ed0096dbb36612d79a2492b2791376029
          packages:
            - 'libqalculate-dev'
            - 'qalc'
